[package]
name = "execution-core"
version = "0.1.0"
edition = "2021"

[dependencies]
dusk-bls12_381 = { version = "0.13", default-features = false, features = ["rkyv-impl"] }
dusk-jubjub = { version = "0.14", default-features = false, features = ["rkyv-impl"] }
dusk-poseidon = "0.39"
bls12_381-bls = { version = "0.3", default-features = false, features = ["rkyv-impl"] }
jubjub-schnorr = { version = "0.4", default-features = false, features = ["rkyv-impl"] }
phoenix-core = { version = "0.30.0-rc", default-features = false, features = ["rkyv-impl", "alloc"] }
dusk-bytes = "0.1"
rkyv = { version = "0.7", default-features = false,  features = ["size_32"] }
bytecheck = { version = "0.6", default-features = false }
rand = { version = "0.8", default-features = false }
ff = { version = "0.13", default-features = false }

[dev-dependencies]
rand = { version = "0.8" }

[features]
# It enables parallel thread aggregation of BlsPublicKey
parallel = ["bls12_381-bls/parallel"]
