[package]
name = "moonlight-contract-types"
description = "Moonlight contract types for the Dusk Network."
version = "0.1.0-rc.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
bls12_381-bls = { version = "0.2", default-features = false, features = ["rkyv-impl"] }
dusk-bytes = "0.1"

rkyv = { version = "0.7", default-features = false, features = ["size_32"] }
bytecheck = { version = "0.6", default-features = false }
