[package]
name = "transfer-data-contract"
version = "0.10.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dusk-bls12_381 = { version = "0.12", default-features = false, features = ["rkyv-impl"] }
dusk-bytes = "0.1"
dusk-pki = { version = "0.13", default-features = false, features = ["rkyv-impl"] }
poseidon-merkle = { version = "0.3", features = ["rkyv-impl"] }
phoenix-core = { version = "0.21", default-features = false, features = ["rkyv-impl", "alloc"] }
rkyv = { version = "0.7", default-features = false, features = ["size_32"] }

[target.'cfg(target_family = "wasm")'.dependencies]
rusk-abi = { version = "0.12.0-rc", path = "../../rusk-abi" }
