[[phoenix_balance]]
address = '4ZH3oyfTuMHyWD1Rp4e7QKp5yK6wLrWvxHneufAiYBAjvereFvfjtDvTbBcZN5ZCsaoMo49s1LKPTwGpowik6QJG'
seed = 0xdead_beef
notes = [100_000_000_000_000]

[[stake]]
address = 'oCqYsUMRqpRn2kSabH52Gt6FQCwH5JXj5MtRdYVtjMSJ73AFvdbPf98p3gz98fQwNy9ZBiDem6m9BivzURKFSKLYWP3N9JahSPZs9PnZ996P18rTGAjQTNFsxtbrKx79yWu'
amount = 1_000_000_000_000

[[phoenix_balance]]
address = '3AiQ4m8tnAMDRTuFxDYfh6vYdJXbbhZgkmKTJHoYBvSFqXChwPjMpZX573KXm9FYPoy47gWYtoybPpPnwYDb8pzs'
seed = 0xcafe_beef
notes = [50_000_000_000_000]
