[package]
name = "rusk"
version = "0.7.0"
edition = "2021"
autobins = false

[lib]
name = "rusk"
path = "src/lib/lib.rs"

[[bin]]
name = "rusk"
path = "src/bin/main.rs"

[dependencies]
tokio = { version = "1.15", features = ["rt-multi-thread", "fs", "macros"] }
futures-util = "0.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3.0", features = [
    "fmt",
    "env-filter",
    "json",
] }
clap = { version = "=4.4", features = ["env", "string", "derive"] }
semver = "1.0"
anyhow = "1.0"
rustc_tools_util = "0.3"
rand = "0.8"
toml = "0.5"
serde = "1"
serde_json = "1"
serde_with = { version = "3.1", features = ["hex"] }
humantime-serde = "1"
bs58 = "0.4"
base64 = "0.22"
hex = "0.4"
parking_lot = "0.12"
rkyv = { version = "0.7", default-features = false, features = ["size_32"] }
bytecheck = { version = "0.6", default-features = false }
dirs = "4"

dusk-schnorr = "0.14"
dusk-poseidon = "0.31"
poseidon-merkle = { version = "0.3", features = ["rkyv-impl", "size_32"] }
sha3 = "0.10"
dusk-plonk = "0.16"
dusk-bls12_381 = "0.12"
dusk-bls12_381-sign = "0.5"
dusk-jubjub = "0.13"
dusk-pki = "0.13"
dusk-bytes = "0.1"
kadcast = "0.6.0-rc"
stake-contract-types = { version = "0.0.1-rc.2", path = "../contracts/stake-types" }
dusk-wallet-core = "0.24.0-plonk.0.16-rc.2"
phoenix-core = { version = "0.21", default-features = false, features = ["rkyv-impl", "alloc"] }
tungstenite = "0.20"
hyper-tungstenite = "0.11"
hyper = { version = "0.14", features = ["server", "stream", "http1", "http2"] }

tokio-stream = "0.1"
tokio-util = { version = "0.7", features = ["rt"] }
tokio-rustls = "0.25"
rustls-pemfile = "2"
async-trait = "0.1"

transfer-circuits = { version = "0.5", path = "../circuits/transfer" }
rusk-profile = { version = "0.6", path = "../rusk-profile" }
rusk-abi = { version = "0.12.0-rc", path = "../rusk-abi", default-features = false, features = ["host"] }
rusk-prover = { version = "0.3", path = "../rusk-prover", optional = true }

## node dependencies
node = { version = "0.1", path = "../node", optional = true }
dusk-consensus = { version = "0.1.1-rc.3", path = "../consensus", optional = true }
node-data = { version = "0.1", path = "../node-data", optional = true }


## GraphQL deps
async-graphql = "5.0"


## Ephemeral dependencies
tempfile = { version = "3.2", optional = true }
rusk-recovery = { version = "0.6", path = "../rusk-recovery", optional = true }

## testwallet dependencies
futures = { version = "0.3", optional = true }

[dev-dependencies]
test-context = "0.1"
reqwest = "0.11"
rusk-recovery = { version = "0.6", path = "../rusk-recovery", features = ["state"] }
ff = { version = "0.13", default-features = false }
rusk-prover = { version = "0.3", path = "../rusk-prover", features = ["no_random"] }
criterion = "0.5"

[build-dependencies]
rustc_tools_util = "0.3"

[features]
default = ["ephemeral", "recovery-state", "recovery-keys", "prover", "node"]
ephemeral = ["dep:rusk-recovery", "dep:tempfile", "recovery-state", "node"]
recovery-state = ["rusk-recovery/state", "dep:tempfile"]
recovery-keys = ["rusk-recovery/keys"]
prover = ["dep:rusk-prover"]
testwallet = ["dep:futures"]
node = ["dep:node", "dep:dusk-consensus", "dep:node-data"]

[[bench]]
name = "block_ingestion"
harness = false
required-features = ["testwallet"]
