# log_level = 'info'
# log_type = 'coloured'
# log_filter = 'dusk_consensus=debug'

[http]
#listen = true
#listen_address = '127.0.0.1:8080'
#cert = <path_of_pem>
#key = <path_of_key>

[chain]
#db_path = '/home/user/.dusk/rusk'
#consensus_keys_path = '/home/user/.dusk/rusk/consensus.keys'
#generation_timeout = '3s'
# Note: changing the gas per deploy byte parameter is equivalent to forking the chain.
#charge_per_deploy_byte = 20000

[databroker]
max_inv_entries = 100
max_ongoing_requests = 1000

[kadcast]
public_address = '127.0.0.1:9000'
# listen_address = '127.0.0.1:9000'
bootstrapping_nodes = []
auto_propagate = true
channel_size = 1000
recursive_discovery = true

[kadcast.bucket]
node_ttl = '30s'
node_evict_after = '5s'
bucket_ttl = '1h'

[kadcast.network]
udp_recv_buffer_size = 5000000
# udp_send_backoff_timeout = '50us'
udp_send_retry_interval = '5ms'
udp_send_retry_count = 3
blocklist_refresh_interval = '10s'

[kadcast.fec.encoder]
min_repair_packets_per_block = 5
mtu = 1300
fec_redundancy = 0.15

[kadcast.fec.decoder]
cache_ttl = '1m'
cache_prune_every = '5m'
